language: generic
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - echo $SHA
  - docker build -t varundunga/react-test -f ./complex/client/Dockerfile.dev ./complex/client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

script:
  - docker run varundunga/react-test npm test -- --coverage


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
